### ISSUE TITLE
consider adding: RoCo: Dialectic Multi-Robot Collaboration with Large Language Models

### ISSUE THREAD

**Issue by MandiZhao** [JeffreyYH/robotics-fm-survey#4]
Please consider adding our work: 
RoCo: Dialectic Multi-Robot Collaboration with Large Language Models, arxiv, 2023, [[Paper](https://arxiv.org/abs/2307.04738)][[Code](https://github.com/MandiZhao/robot-collab)][[Website](https://project-roco.github.io/)]

Thank you!

**Comment by JeffreyYH** [comment]
Hi Mandi, thank you for your suggestion! Currently, we do not have a multi-robot category, so I will put this paper in the task planning category. The change on the paper may be reflected on the next version.

Best,
