### ISSUE TITLE
EMMA - EMNLP 2023

### ISSUE THREAD

**Issue by aleSuglia** [JeffreyYH/robotics-fm-survey#6]
Hello,

Thanks for putting together this nice survey paper. I would like to suggest citing the following paper that presents EMMA, a V+L foundation model for robotics tasks that was one of the finalists in the [Amazon Simbot Challenge](https://www.amazon.science/alexa-prize/simbot-challenge).

https://aclanthology.org/2023.emnlp-main.50.pdf

**Comment by JeffreyYH** [comment]
So sorry for the late reply. We are not able to include this paper since it does not have real-robot or high-fidelity simulation experiments.
